import { Palette } from "std-widgets.slint";

export global AppPalette {
    out property <color> primary-main: Palette.alternate-foreground;
    out property <color> primary-contrast: Palette.alternate-background;

    out property <color> secondary-main: #01c298;
    out property <color> secondary-contrast: #ffffff;

    out property <color> on-primary: #ffffff;
    out property <color> on-secondary: #13202c;

    out property <color> background: Palette.background;
    out property <color> border: Palette.border;
}
