import { AppPalette } from "../theme.slint";
import { TableViewStyle } from "table-view.style.slint";
import { TableViewColumnData } from "table-view.types.slint";

export component TableViewRow inherits Rectangle {
    in property <[TableViewColumnData]> cols: [
        {
            header: "Default header",
            values: ["Default value"],
            width: 100px,
            min_width: 50px,
            max_width: 200px,
            resizable: true,
        }
    ];
    in property <int> row_index: 0;

    height: 30px;

    HorizontalLayout {

        for col[idx] in root.cols: Rectangle {
            property <length> col_width: col.width == 0 ? TableViewStyle.default_col_width : col.width;
            width: col_width;
            height: parent.height;
            background: transparent;
            clip: true;

            Text {
                width: parent.width;
                horizontal-alignment: TextHorizontalAlignment.start;
                vertical-alignment: TextVerticalAlignment.top;
                overflow: TextOverflow.elide;
                text: col.values[root.row_index];
            }
        }

        coL_spacer := Rectangle {
            horizontal-stretch: 1;
            background: transparent;
        }
    }

    Rectangle {
        y: parent.height - 1px;
        width: parent.width;
        height: 1px;
        background: AppPalette.border;
    }
}
