export global ControlBarStyle {
    out property <length> control_row_height: 38px;
}

export global ControlButtonStyle {
    out property <length> control_button_size: 34px;
    out property <length> control_button_spacing: 6px;
    out property <color> record_button_color: #b80000;
    out property <color> stop_button_color: #0000b8;
    out property <color> play_button_color: #01c231;
}

export global ControlInputStyle {
    out property <length> input_field_height: 24px;
    out property <length> input_field_width: 40px;
    out property <length> input_icon_size: 20px;
    out property <length> input_spacing: 6px;
}
