import {
    Button,
    ComboBox,
    HorizontalBox,
    ScrollView,
    VerticalBox,
} from "std-widgets.slint";
import { SquareIconButton } from "../components/square-icon-button.slint";
import { SessionControlsStyle } from "editor-view.style.slint";
import { AppPalette } from "../theme.slint";
import { TableView } from "../components/table-view.slint";

export component EditorView inherits Rectangle {

    in property <bool> has_recordings: false;
    in property <[string]> recording_titles: [];
    in property <int> selected_recording_index: -1;
    in property <string> selected_recording_title;
    in property <[string]> event_index_labels: [];
    in property <[string]> event_type_labels: [];
    in property <[string]> event_parameter_labels: [];
    in property <[string]> event_duration_labels: [];
    in property <bool> filter_key_events_selected: true;
    in property <bool> filter_mouse_button_events_selected: true;
    in property <bool> filter_mouse_wheel_events_selected: true;
    in property <bool> filter_pointer_move_events_selected: false;
    in property <string> filter_key_event_count_label: "0";
    in property <string> filter_mouse_button_event_count_label: "0";
    in property <string> filter_mouse_wheel_event_count_label: "0";
    in property <string> filter_pointer_move_event_count_label: "0";
    in property <bool> can_save_editor_changes: false;
    in property <bool> can_revert_editor_changes: false;
    in property <bool> can_delete_selected_recording: false;
    callback refresh_library_requested();
    callback select_recording_requested(index: int);
    callback delete_selected_recording_requested();
    callback save_editor_changes_requested();
    callback revert_editor_changes_requested();
    callback filter_key_events_requested(enabled: bool);
    callback filter_mouse_button_events_requested(enabled: bool);
    callback filter_mouse_wheel_events_requested(enabled: bool);
    callback filter_pointer_move_events_requested(enabled: bool);

    VerticalLayout {
        alignment: LayoutAlignment.stretch;
        padding: 4px;
        spacing: 4px;

        session_controls := HorizontalLayout {
            alignment: LayoutAlignment.end;
            spacing: 4px;

            SquareIconButton {
                icon: @image-url("../../assets/icons/RefreshIcon.svg");
                size: SessionControlsStyle.button_size;
                clicked => {
                    root.refresh_library_requested();
                }
            }

            ComboBox {
                enabled: root.has_recordings;
                height: SessionControlsStyle.combo_box_height;
                model: root.recording_titles;
                current-index: root.selected_recording_index < 0 ? 0 : root.selected_recording_index;
                current-value: root.selected_recording_title;
                selected => {
                    root.select_recording_requested(self.current-index);
                }
            }

            SquareIconButton {
                icon: @image-url("../../assets/icons/CheckIcon.svg");
                size: SessionControlsStyle.button_size;
                enabled: root.can_save_editor_changes;
                clicked => {
                    root.save_editor_changes_requested();
                }
            }

            SquareIconButton {
                icon: @image-url("../../assets/icons/CancelIcon.svg");
                size: SessionControlsStyle.button_size;
                enabled: root.can_revert_editor_changes;
                clicked => {
                    root.revert_editor_changes_requested();
                }
            }

            SquareIconButton {
                icon: @image-url("../../assets/icons/DeleteIcon.svg");
                size: SessionControlsStyle.button_size;
                enabled: root.can_delete_selected_recording;
                clicked => {
                    root.delete_selected_recording_requested();
                }
            }
        }

        filter_buttons := HorizontalLayout {
            spacing: 4px;

            Button {
                icon: @image-url("../../assets/icons/KeyboardIcon.svg");
                colorize-icon: true;
                text: root.filter_key_event_count_label;
                primary: root.filter_key_events_selected;
                height: SessionControlsStyle.button_size;
                clicked => {
                    root.filter_key_events_requested(!root.filter_key_events_selected);
                }
            }

            Button {
                icon: @image-url("../../assets/icons/MouseButtonIcon.svg");
                colorize-icon: true;
                text: root.filter_mouse_button_event_count_label;
                primary: root.filter_mouse_button_events_selected;
                height: SessionControlsStyle.button_size;
                clicked => {
                    root.filter_mouse_button_events_requested(!root.filter_mouse_button_events_selected);
                }
            }

            Button {
                icon: @image-url("../../assets/icons/MouseScrollWheelIcon.svg");
                colorize-icon: true;
                text: root.filter_mouse_wheel_event_count_label;
                primary: root.filter_mouse_wheel_events_selected;
                height: SessionControlsStyle.button_size;
                clicked => {
                    root.filter_mouse_wheel_events_requested(!root.filter_mouse_wheel_events_selected);
                }
            }

            Button {
                icon: @image-url("../../assets/icons/MouseMoveIcon.svg");
                colorize-icon: true;
                text: root.filter_pointer_move_event_count_label;
                primary: root.filter_pointer_move_events_selected;
                height: SessionControlsStyle.button_size;
                clicked => {
                    root.filter_pointer_move_events_requested(!root.filter_pointer_move_events_selected);
                }
            }
        }

        TableView {
            border-width: 1px;
            border-color: AppPalette.border;
            vertical-stretch: 1;
            horizontal-stretch: 1;

            cols: [
                { header: "#", values: root.event_index_labels, width: 42px, resizable: true },
                { header: "Type", values: root.event_type_labels, width: 100px, resizable: true },
                {
                    header: "Parameters",
                    values: root.event_parameter_labels,
                    width: 100px,
                    resizable: true
                },
                { header: "Duration", values: root.event_duration_labels, width: 100px, resizable: true },
            ];
        }
    }
}
