import { VerticalBox } from "std-widgets.slint";
import { IconButton } from "../components/icon-button.slint";
import { Theme } from "../theme.slint";

export component SidebarNav inherits Rectangle {
    in property <bool> editor_tab_selected: true;
    in property <bool> diagnostics_tab_selected: false;
    in property <bool> settings_tab_selected: false;
    callback show_editor_requested();
    callback show_diagnostics_requested();
    callback show_settings_requested();

    width: 40px;
    background: Theme.nav-background;

    VerticalBox {
        padding: 4px;
        spacing: 6px;

        IconButton {
            icon: @image-url("../../assets/icons/EditIcon.svg");
            control_accessible_label: "Open event editor";
            button_width: 32px;
            button_height: 32px;
            selected: root.editor_tab_selected;
            tapped => {
                root.show_editor_requested();
            }
        }

        IconButton {
            icon: @image-url("../../assets/icons/DiagnosticIcon.svg");
            control_accessible_label: "Open diagnostics";
            button_width: 32px;
            button_height: 32px;
            selected: root.diagnostics_tab_selected;
            tapped => {
                root.show_diagnostics_requested();
            }
        }

        IconButton {
            icon: @image-url("../../assets/icons/SettingsIcon.svg");
            control_accessible_label: "Open settings";
            button_width: 32px;
            button_height: 32px;
            selected: root.settings_tab_selected;
            tapped => {
                root.show_settings_requested();
            }
        }

        Rectangle {
            vertical-stretch: 1;
            background: transparent;
        }
    }
}
